### ISSUE TITLE
Develop instructions

### ISSUE THREAD

**Issue by tgerring** [TruthBean/ffmpeg-nodejs#1]
Hello! This is a very interesting project and I am trying to learn more about. I attempted to compile both on Mac and Ubuntu and ran into some errors that I hope you could help with.

First, in the documentation it should be mentioned that `yasm` is is required installed along with clang and other packages. Also, it would be helpful to note `cmake .` is required before running `make`. Still, I am unable to produce a working build. The error I receive on Mac is:

```
~/dev/ffmpeg-nodejs/src/./node_api.h:9:10: fatal error: 'node/node_api.h' file not found
```

Ubuntu error is:
```
/usr/include/node/uv/unix.h:45:10: fatal error: uv/threadpool.h: No such file or directory
```

This is obviously about some required files not being located, however I cannot find anything when searching for the error and have not had luck trying to symlink nodejs source as a monkey patch.

Is there any more information you could provide to help me produce a working build? I would like to PR a README update with any additional developer information to help others.

Thank you!

**Comment by TruthBean** [comment]
I need say sorry first that I cannot reply your question directly, secondly，and so  shameful is that my english is so pool to hard write those words.

I code this because i did need ffmpeg to grab image from video stream, specially rtsp stream.

FFmpeg compiles depend to yasm, you need install first. Or you can install ffmpeg library dev, like avcodec-dev, and etc. Then, the project need nodejs, I used global env nodejs. And the last, I use ffmpeg 4.x      3.x and below is not work.

Thanths for your question and attempt，by the way, I coding java for now, and I try to write all detail in REAME next commit soon.

**Comment by tgerring** [comment]
Thank you!

**Comment by TruthBean** [comment]
I have committed something to develop branch, you can see it now
